CREATE TABLE LOGIN_USER (
  userid INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  userName VARCHAR(50) NOT NULL,
  password VARCHAR(100) NOT NULL,
  role VARCHAR(10) NOT NULL
);

INSERT INTO LOGIN_USER(userName, password, role) VALUES ('admin', '$2a$04$S5yLjTnnhMLhcvM8qXVLpul1LGP4b192QfJb8U4XQ3GUQMTSiCCQy', 'ADMIN');
INSERT INTO LOGIN_USER(userName, password, role) VALUES ('systemUser', '$2a$04$S5yLjTnnhMLhcvM8qXVLpul1LGP4b192QfJb8U4XQ3GUQMTSiCCQy', 'ADMIN');
INSERT INTO LOGIN_USER(userName, password, role) VALUES ('guest', '$2a$04$S5yLjTnnhMLhcvM8qXVLpul1LGP4b192QfJb8U4XQ3GUQMTSiCCQy', 'ADMIN');